services:

  wordpress:
    image: wordpress:latest
    container_name: wp1
    hostname: wordpress
    restart: unless-stopped
    ports:
      - "8101:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: useradmin
      WORDPRESS_DB_PASSWORD: p4ssw0rd
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - red_wp1

  db:
    image: mariadb:latest
    container_name: db_wp1
    hostname: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: useradmin
      MYSQL_PASSWORD: p4ssw0rd
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - red_wp1

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_wp1
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd
      PMA_USER: useradmin
      PMA_PASSWORD: p4ssw0rd
    networks:
      - red_wp1

networks:
  red_wp1:

